// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Web.Api.Data;

#nullable disable

namespace Project.Web.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project.Web.Api.Models.Categoria_Jogos", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JogoId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("JogoId");

                    b.ToTable("Categoria_Jogos");
                });

            modelBuilder.Entity("Project.Web.Api.Models.Jogos", b =>
                {
                    b.Property<int>("ID_Jogo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Jogo"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Jogo");

                    b.ToTable("Biblioteca_Jogos");
                });

            modelBuilder.Entity("Project.Web.Api.Models.Categoria_Jogos", b =>
                {
                    b.HasOne("Project.Web.Api.Models.Jogos", "Jogos")
                        .WithMany("Categoria")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogos");
                });

            modelBuilder.Entity("Project.Web.Api.Models.Jogos", b =>
                {
                    b.Navigation("Categoria");
                });
#pragma warning restore 612, 618
        }
    }
}
